stages:
  - install
  - codecheck

default:
  image: node:18

  # Cache modules in between jobs
cache:
  key: cache-$CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - .next/

# Install Depentencies like node_modules
install_depentencies:
  stage: install
  script:
    - yarn install

# Job to run lints
lint:
  stage: codecheck
  script:
    - yarn lint

# Job to run Unit Tests
test:
  stage: codecheck
  script:
    - yarn test

# Job to check typescript types
typecheck:
  stage: codecheck
  script:
    - yarn tsc
